config/routes.rb
Rails.application.routes.draw do
  resources :authorities
  resources :login_records
  resources :purchase_records

end

app/models/authority.rb
class Authority
  include Mongoid::Document
  include Mongoid::Timestamps

  field :id, type: Integer
  field :name, type: String
  field :subId, type: Integer
  field :code, type: Integer
  field :description, type: String
  field :authority_groupId, type: Integer
end

app/models/login_record.rb
class LoginRecord
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :id, type: Integer
  field :source, type: String
  field :datetime, type: DateTime
end

app/models/purchase_record.rb
class PurchaseRecord
  include Mongoid::Document
  include Mongoid::Timestamps

  field :id, type: Integer
  field :source, type: String
  field :datetime, type: String
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/authorities_controller.rb
class AuthoritiesController < ApplicationController
  before_action :set_authority, only: [:show, :edit, :update, :destroy]

  # GET /authorities
  # GET /authorities.json
  def index
    @authorities = Authority.all
  end

  # GET /authorities/1
  # GET /authorities/1.json
  def show
  end

  # GET /authorities/new
  def new
    @authority = Authority.new
  end

  # GET /authorities/1/edit
  def edit
  end

  # POST /authorities
  # POST /authorities.json
  def create
    @authority = Authority.new(authority_params)

    respond_to do |format|
      if @authority.save
        format.html { redirect_to @authority, notice: 'Authority was successfully created.' }
        format.json { render :show, status: :created, location: @authority }
      else
        format.html { render :new }
        format.json { render json: @authority.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authorities/1
  # PATCH/PUT /authorities/1.json
  def update
    respond_to do |format|
      if @authority.update(authority_params)
        format.html { redirect_to @authority, notice: 'Authority was successfully updated.' }
        format.json { render :show, status: :ok, location: @authority }
      else
        format.html { render :edit }
        format.json { render json: @authority.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authorities/1
  # DELETE /authorities/1.json
  def destroy
    @authority.destroy
    respond_to do |format|
      format.html { redirect_to authorities_url, notice: 'Authority was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_authority
      @authority = Authority.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def authority_params
      params.require(:authority).permit(:id, :name, :subId, :code, :description, :authority_groupId)
    end
end

app/controllers/login_records_controller.rb
class LoginRecordsController < ApplicationController
  before_action :set_login_record, only: [:show, :edit, :update, :destroy]

  # GET /login_records
  # GET /login_records.json
  def index
    @login_records = LoginRecord.all
  end

  # GET /login_records/1
  # GET /login_records/1.json
  def show
  end

  # GET /login_records/new
  def new
    @login_record = LoginRecord.new
  end

  # GET /login_records/1/edit
  def edit
  end

  # POST /login_records
  # POST /login_records.json
  def create
    @login_record = LoginRecord.new(login_record_params)

    respond_to do |format|
      if @login_record.save
        format.html { redirect_to @login_record, notice: 'Login record was successfully created.' }
        format.json { render :show, status: :created, location: @login_record }
      else
        format.html { render :new }
        format.json { render json: @login_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /login_records/1
  # PATCH/PUT /login_records/1.json
  def update
    respond_to do |format|
      if @login_record.update(login_record_params)
        format.html { redirect_to @login_record, notice: 'Login record was successfully updated.' }
        format.json { render :show, status: :ok, location: @login_record }
      else
        format.html { render :edit }
        format.json { render json: @login_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /login_records/1
  # DELETE /login_records/1.json
  def destroy
    @login_record.destroy
    respond_to do |format|
      format.html { redirect_to login_records_url, notice: 'Login record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login_record
      @login_record = LoginRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_record_params
      params.require(:login_record).permit(:id, :source, :datetime)
    end
end

app/controllers/purchase_records_controller.rb
class PurchaseRecordsController < ApplicationController
  before_action :set_purchase_record, only: [:show, :edit, :update, :destroy]

  # GET /purchase_records
  # GET /purchase_records.json
  def index
    @purchase_records = PurchaseRecord.all
  end

  # GET /purchase_records/1
  # GET /purchase_records/1.json
  def show
  end

  # GET /purchase_records/new
  def new
    @purchase_record = PurchaseRecord.new
  end

  # GET /purchase_records/1/edit
  def edit
  end

  # POST /purchase_records
  # POST /purchase_records.json
  def create
    @purchase_record = PurchaseRecord.new(purchase_record_params)

    respond_to do |format|
      if @purchase_record.save
        format.html { redirect_to @purchase_record, notice: 'Purchase record was successfully created.' }
        format.json { render :show, status: :created, location: @purchase_record }
      else
        format.html { render :new }
        format.json { render json: @purchase_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /purchase_records/1
  # PATCH/PUT /purchase_records/1.json
  def update
    respond_to do |format|
      if @purchase_record.update(purchase_record_params)
        format.html { redirect_to @purchase_record, notice: 'Purchase record was successfully updated.' }
        format.json { render :show, status: :ok, location: @purchase_record }
      else
        format.html { render :edit }
        format.json { render json: @purchase_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /purchase_records/1
  # DELETE /purchase_records/1.json
  def destroy
    @purchase_record.destroy
    respond_to do |format|
      format.html { redirect_to purchase_records_url, notice: 'Purchase record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_purchase_record
      @purchase_record = PurchaseRecord.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def purchase_record_params
      params.require(:purchase_record).permit(:id, :source, :datetime)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authorities_helper.rb
module AuthoritiesHelper
end

app/helpers/login_records_helper.rb
module LoginRecordsHelper
end

app/helpers/purchase_records_helper.rb
module PurchaseRecordsHelper
end

app/views/authorities/_form.html.erb
<%= form_for(@authority) do |f| %>
  <% if @authority.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@authority.errors.count, "error") %> prohibited this authority from being saved:</h2>

      <ul>
      <% @authority.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :subId %><br>
    <%= f.text_field :subId %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :authority_groupId %><br>
    <%= f.text_field :authority_groupId %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/authorities/edit.html.erb
<h1>Editing Authority</h1>

<%= render 'form' %>

<%= link_to 'Show', @authority %> |
<%= link_to 'Back', authorities_path %>

app/views/authorities/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Authorities</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Subid</th>
      <th>Code</th>
      <th>Description</th>
      <th>Authority groupid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authorities.each do |authority| %>
      <tr>
        <td><%= authority.id %></td>
        <td><%= authority.name %></td>
        <td><%= authority.subId %></td>
        <td><%= authority.code %></td>
        <td><%= authority.description %></td>
        <td><%= authority.authority_groupId %></td>
        <td><%= link_to 'Show', authority %></td>
        <td><%= link_to 'Edit', edit_authority_path(authority) %></td>
        <td><%= link_to 'Destroy', authority, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Authority', new_authority_path %>

app/views/authorities/new.html.erb
<h1>New Authority</h1>

<%= render 'form' %>

<%= link_to 'Back', authorities_path %>

app/views/authorities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @authority.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @authority.name %>
</p>

<p>
  <strong>Subid:</strong>
  <%= @authority.subId %>
</p>

<p>
  <strong>Code:</strong>
  <%= @authority.code %>
</p>

<p>
  <strong>Description:</strong>
  <%= @authority.description %>
</p>

<p>
  <strong>Authority groupid:</strong>
  <%= @authority.authority_groupId %>
</p>

<%= link_to 'Edit', edit_authority_path(@authority) %> |
<%= link_to 'Back', authorities_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PocPo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/login_records/_form.html.erb
<%= form_for(@login_record) do |f| %>
  <% if @login_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login_record.errors.count, "error") %> prohibited this login_record from being saved:</h2>

      <ul>
      <% @login_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :datetime %><br>
    <%= f.text_field :datetime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/login_records/edit.html.erb
<h1>Editing Login Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @login_record %> |
<%= link_to 'Back', login_records_path %>

app/views/login_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Login Records</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Source</th>
      <th>Datetime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @login_records.each do |login_record| %>
      <tr>
        <td><%= login_record.id %></td>
        <td><%= login_record.source %></td>
        <td><%= login_record.datetime %></td>
        <td><%= link_to 'Show', login_record %></td>
        <td><%= link_to 'Edit', edit_login_record_path(login_record) %></td>
        <td><%= link_to 'Destroy', login_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Login record', new_login_record_path %>

app/views/login_records/new.html.erb
<h1>New Login Record</h1>

<%= render 'form' %>

<%= link_to 'Back', login_records_path %>

app/views/login_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @login_record.id %>
</p>

<p>
  <strong>Source:</strong>
  <%= @login_record.source %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @login_record.datetime %>
</p>

<%= link_to 'Edit', edit_login_record_path(@login_record) %> |
<%= link_to 'Back', login_records_path %>

app/views/purchase_records/_form.html.erb
<%= form_for(@purchase_record) do |f| %>
  <% if @purchase_record.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@purchase_record.errors.count, "error") %> prohibited this purchase_record from being saved:</h2>

      <ul>
      <% @purchase_record.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :datetime %><br>
    <%= f.text_field :datetime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/purchase_records/edit.html.erb
<h1>Editing Purchase Record</h1>

<%= render 'form' %>

<%= link_to 'Show', @purchase_record %> |
<%= link_to 'Back', purchase_records_path %>

app/views/purchase_records/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Purchase Records</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Source</th>
      <th>Datetime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @purchase_records.each do |purchase_record| %>
      <tr>
        <td><%= purchase_record.id %></td>
        <td><%= purchase_record.source %></td>
        <td><%= purchase_record.datetime %></td>
        <td><%= link_to 'Show', purchase_record %></td>
        <td><%= link_to 'Edit', edit_purchase_record_path(purchase_record) %></td>
        <td><%= link_to 'Destroy', purchase_record, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Purchase record', new_purchase_record_path %>

app/views/purchase_records/new.html.erb
<h1>New Purchase Record</h1>

<%= render 'form' %>

<%= link_to 'Back', purchase_records_path %>

app/views/purchase_records/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @purchase_record.id %>
</p>

<p>
  <strong>Source:</strong>
  <%= @purchase_record.source %>
</p>

<p>
  <strong>Datetime:</strong>
  <%= @purchase_record.datetime %>
</p>

<%= link_to 'Edit', edit_purchase_record_path(@purchase_record) %> |
<%= link_to 'Back', purchase_records_path %>